<a href="https://colab.research.google.com/github/Vinoth1512/ML-PROJECTS/blob/main/DAY19(NAIVE_BAYES)Multinomial.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [149]:
import numpy as np 
import pandas as pd
import sklearn
from sklearn.datasets import fetch_20newsgroups

In [150]:
news=fetch_20newsgroups()


In [151]:
news.keys()

dict_keys(['data', 'filenames', 'target_names', 'target', 'DESCR'])

In [152]:
news.target

array([7, 4, 4, ..., 3, 1, 8])

In [153]:
print(news.target_names)

['alt.atheism', 'comp.graphics', 'comp.os.ms-windows.misc', 'comp.sys.ibm.pc.hardware', 'comp.sys.mac.hardware', 'comp.windows.x', 'misc.forsale', 'rec.autos', 'rec.motorcycles', 'rec.sport.baseball', 'rec.sport.hockey', 'sci.crypt', 'sci.electronics', 'sci.med', 'sci.space', 'soc.religion.christian', 'talk.politics.guns', 'talk.politics.mideast', 'talk.politics.misc', 'talk.religion.misc']


In [154]:
dir(news)

['DESCR', 'data', 'filenames', 'target', 'target_names']

In [155]:
cats=news.target_names[:4]
cats


['alt.atheism',
 'comp.graphics',
 'comp.os.ms-windows.misc',
 'comp.sys.ibm.pc.hardware']

In [166]:
#TO GET FEATURE VECTOR
from sklearn.feature_extraction.text import CountVectorizer
count_vector=CountVectorizer()
news_train=fetch_20newsgroups(subset='train',categories=cats)
news_test=fetch_20newsgroups(subset='test',categories=cats)

In [167]:
xtrain=count_vector.fit_transform(news_train.data)
print(xtrain.shape)


(2245, 62227)


In [168]:
xtest=count_vector.transform(news_test.data)
print(xtest.shape)

(1494, 62227)


In [170]:
#TO GET WEIGHTAGE 
from sklearn.feature_extraction.text import TfidfTransformer
tfidf=TfidfTransformer()
xtrain_tfidf=tfidf.fit_transform(xtrain)
xtest_tfidf=tfidf.transform(xtest)
xtrain_tfidf.shape

(2245, 62227)

In [171]:
from sklearn.naive_bayes import MultinomialNB
model=MultinomialNB()
model.fit(xtrain_tfidf,news_train.target)

MultinomialNB(alpha=1.0, class_prior=None, fit_prior=True)

In [172]:
pred=model.predict(xtest_tfidf)
pred

array([1, 2, 1, ..., 1, 3, 3])

In [176]:
from sklearn.metrics import confusion_matrix,accuracy_score
accuracy_score(pred,news_test.target)*100

85.20749665327979

In [177]:
confusion_matrix(pred,news_test.target)

array([[312,  12,  16,   1],
       [  2, 319,  26,   8],
       [  1,  22, 277,  18],
       [  4,  36,  75, 365]])

In [162]:
#SIMPLE EXAMPLE FOR COUNTVECTORIZER
from sklearn.feature_extraction.text import CountVectorizer
corpus = [
     'This is the first document.',
     'This document is the second document.',
     'And this is the third one.',
     'Is this the first document?',
 ]
vectorizer=CountVectorizer()
X=vectorizer.fit_transform(corpus)
vectorizer.get_feature_names()


['and', 'document', 'first', 'is', 'one', 'second', 'the', 'third', 'this']

In [ ]:
print(X.toarray())

[[0 1 1 1 0 0 1 0 1]
 [0 2 0 1 0 1 1 0 1]
 [1 0 0 1 1 0 1 1 1]
 [0 1 1 1 0 0 1 0 1]]


In [ ]:
df=pd.DataFrame(X.toarray(),columns=vectorizer.get_feature_names())
df

and  document  first  is  one  second  the  third  this
0    0         1      1   1    0       0    1      0     1
1    0         2      0   1    0       1    1      0     1
2    1         0      0   1    1       0    1      1     1
3    0         1      1   1    0       0    1      0     1