<a href="https://colab.research.google.com/github/Vinoth1512/ML-PROJECTS/blob/main/DAY19(NAIVE_BAYES)Multinomial.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np 
import pandas as pd
import sklearn
from sklearn.datasets import fetch_20newsgroups

In [2]:
news=fetch_20newsgroups()


In [3]:
news.keys()

dict_keys(['data', 'filenames', 'target_names', 'target', 'DESCR'])

In [4]:
print(news.target_names)

['alt.atheism', 'comp.graphics', 'comp.os.ms-windows.misc', 'comp.sys.ibm.pc.hardware', 'comp.sys.mac.hardware', 'comp.windows.x', 'misc.forsale', 'rec.autos', 'rec.motorcycles', 'rec.sport.baseball', 'rec.sport.hockey', 'sci.crypt', 'sci.electronics', 'sci.med', 'sci.space', 'soc.religion.christian', 'talk.politics.guns', 'talk.politics.mideast', 'talk.politics.misc', 'talk.religion.misc']


In [5]:
dir(news)

['DESCR', 'data', 'filenames', 'target', 'target_names']

In [6]:
cats=news.target_names[-4:]
cats


['talk.politics.guns',
 'talk.politics.mideast',
 'talk.politics.misc',
 'talk.religion.misc']

In [7]:
#TO GET FEATURE VECTOR
from sklearn.feature_extraction.text import CountVectorizer
count_vector=CountVectorizer()
news_train=fetch_20newsgroups(subset='train',categories=cats)
news_test=fetch_20newsgroups(subset='test',categories=cats)

In [8]:
xtrain=count_vector.fit_transform(news_train.data)
print(xtrain.shape)


(1952, 36379)


In [9]:
#TO GET WEIGHTAGE 
from sklearn.feature_extraction.text import TfidfTransformer
tfidf=TfidfTransformer()
xtrain_tfidf=tfidf.fit_transform(xtrain)
xtrain_tfidf.shape

(1952, 36379)

In [10]:
from sklearn.naive_bayes import MultinomialNB
model=MultinomialNB().fit(xtrain_tfidf,news_train.target)




In [11]:
x_test_df=count_vector.transform(news_test.data)
x_test_tfidf=tfidf.transform(x_test_df)

pred=model.predict(x_test_tfidf)
pred

array([0, 1, 0, ..., 3, 0, 0])

In [12]:
#SIMPLE EXAMPLE FOR COUNTVECTORIZER
from sklearn.feature_extraction.text import CountVectorizer
corpus = [
     'This is the first document.',
     'This document is the second document.',
     'And this is the third one.',
     'Is this the first document?',
 ]
vectorizer=CountVectorizer()
X=vectorizer.fit_transform(corpus)
vectorizer.get_feature_names()


['and', 'document', 'first', 'is', 'one', 'second', 'the', 'third', 'this']

In [13]:
print(X.toarray())

[[0 1 1 1 0 0 1 0 1]
 [0 2 0 1 0 1 1 0 1]
 [1 0 0 1 1 0 1 1 1]
 [0 1 1 1 0 0 1 0 1]]


In [14]:
df=pd.DataFrame(X.toarray(),columns=vectorizer.get_feature_names())
df

and  document  first  is  one  second  the  third  this
0    0         1      1   1    0       0    1      0     1
1    0         2      0   1    0       1    1      0     1
2    1         0      0   1    1       0    1      1     1
3    0         1      1   1    0       0    1      0     1